In [1]:
import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API키 로드 완료 : {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API키 로드 완료 : 6949fb...c67e

In [11]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

In [16]:
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type': 'json'})
response.raise_for_status() # HTTP 오류 목록 알려준다.

In [17]:
print(response.status_code) # 상태 확인 -> 200으로 나오면 정상

200

In [18]:
response = requests.get('http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList',
                        params={'serviceKey':API_KEY, '_type':'json'})
response

In [19]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': '', 'numOfRows': 10, 'pageNo': 1, 'totalCount': 0}}}

In [26]:
response = requests.get(BASE_URL, params={'serviceKey': API_KEY,
                                          'pageNo':1,
                                          'numOfRows':10,
                                          '_type':'json',   # json 형식
                                          'cityCode': 22,
                                          'nodeid':'DGB7061040400'})   
response

In [27]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '금강동',
      'routeid': 'DGB3000848001',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000609007',
      'routeno': 609,
      'routetp': '간선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '부적주공A 건너',
      'routeid': 'DGB3000309002',
      'routeno': 309,
      'routetp': '간선버스',
      'startnodenm': '서대구역(남측)1'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848000',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000649000',
      'routeno': 649,
      'routetp': '간선버스',
      'startnodenm': '대곡공원앞'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848003',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '소라아파트 건너',
      'routeid': 'DGB3000509002',
      'routeno': 509,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848002',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 8}}}

In [28]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
NODE_ID = 'DGB7061040400'
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 30

In [40]:
BASE_DIR = os.getcwd()  # 현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'route_by_stop.csv')

In [41]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb'
TABLE_NAME = 'route_by_stop'

print(f'csv저장경로 : {OUTPUT_PATH}')

csv저장경로 : c:\Users\Administrator\bigdata2026\fastapi\03_bus_api_pipeline\output\route_by_stop.csv

In [31]:
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '금강동',
      'routeid': 'DGB3000848001',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000609007',
      'routeno': 609,
      'routetp': '간선버스',
      'startnodenm': '대천공영차고지앞'},
     {'endnodenm': '부적주공A 건너',
      'routeid': 'DGB3000309002',
      'routeno': 309,
      'routetp': '간선버스',
      'startnodenm': '서대구역(남측)1'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848000',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '금구동(종점)',
      'routeid': 'DGB3000649000',
      'routeno': 649,
      'routetp': '간선버스',
      'startnodenm': '대곡공원앞'},
     {'endnodenm': '금강동',
      'routeid': 'DGB3000848003',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '동호공영차고지앞'},
     {'endnodenm': '소라아파트 건너',
      'routeid': 'DGB3000509002',
      'routeno': 509,
      'routetp': '간선버스',
      'startnodenm': '방천리공영차고지'},
     {'endnodenm': '동호공영차고지건너',
      'routeid': 'DGB3000848002',
      'routeno': 848,
      'routetp': '간선버스',
      'startnodenm': '금강동'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 8}}}

In [32]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count / ROWS_PER_PAGE)

print(f'전체 건수 : {total_count:,}개')
print(f'페이지당 건수 : {ROWS_PER_PAGE:,}개')
print(f'총 페이지 수 : {total_pages}페이지')

전체 건수 : 8개
페이지당 건수 : 1,000개
총 페이지 수 : 1페이지

In [33]:
all_itmes = []

for page_no in range(1, total_pages+1):
    params={
        'serviceKey': API_KEY,
        'pageNo': page_no,
        'numOfRows': ROWS_PER_PAGE,
        'cityCode': CITY_CODE,
        '_type': 'json',
        'nodeid': NODE_ID
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    # 마지막 페이지나 오류 상황에서는 items가 비어있을 수 있다.
    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue # 아래로 내려가지 않고, 다음 페이지(순서)로 간다

    page_itmes = page_body['items'].get('item', []) # 없으면 빈 리스트

    if isinstance(page_itmes, dict):
        page_itmes = [page_itmes] # 딕셔너리가 맞다면 리스트 형태로 저장

    all_itmes.extend(page_itmes) # 여러개를 맨 뒤에 한꺼번에 추가하는 리스트함수

    print(f'{page_no} / {total_pages} 페이지 수집 완료 -> 누적 {len(all_itmes):,}건')

    time.sleep(0.2) # 너무 빠르게 요청하지 않게 0.2초 기다린 후 다음 진행

print(f'전체 수집 완료 : {len(all_itmes):,}건')

1 / 1 페이지 수집 완료 -> 누적 8건
전체 수집 완료 : 8건

In [34]:
df_raw = pd.DataFrame(all_itmes)

print(f'데이터프레임의 크기 : {df_raw.shape}')

데이터프레임의 크기 : (8, 5)

In [35]:
# 랜덤 데이터 확인 - sample()
df_raw.sample(5)

   endnodenm        routeid  routeno routetp startnodenm
2   부적주공A 건너  DGB3000309002      309    간선버스   서대구역(남측)1
7  동호공영차고지건너  DGB3000848002      848    간선버스         금강동
4    금구동(종점)  DGB3000649000      649    간선버스       대곡공원앞
0        금강동  DGB3000848001      848    간선버스         금강동
3  동호공영차고지건너  DGB3000848000      848    간선버스    동호공영차고지앞

In [45]:
COLUMN_RENAME = {
    'endnodenm': '종점',
    'routeid': '노선ID',
    'routeno': '노선번호',
    'routetp': '노선유형',
    'startnodenm': '기점'
}
df = df_raw.rename(columns=COLUMN_RENAME)

print(f'변경 후 컬럼 목록 : {df.columns.tolist()}')

변경 후 컬럼 목록 : ['종점', '노선ID', '노선번호', '노선유형', '기점']

In [37]:
df.head()

          종점           노선ID  노선번호  노선유형         기점
0        금강동  DGB3000848001   848  간선버스        금강동
1    금구동(종점)  DGB3000609007   609  간선버스   대천공영차고지앞
2   부적주공A 건너  DGB3000309002   309  간선버스  서대구역(남측)1
3  동호공영차고지건너  DGB3000848000   848  간선버스   동호공영차고지앞
4    금구동(종점)  DGB3000649000   649  간선버스      대곡공원앞

In [47]:
df['node_id'] = NODE_ID

In [48]:
df.head()

          종점           노선ID  노선번호  노선유형         기점        node_id
0        금강동  DGB3000848001   848  간선버스        금강동  DGB7061040400
1    금구동(종점)  DGB3000609007   609  간선버스   대천공영차고지앞  DGB7061040400
2   부적주공A 건너  DGB3000309002   309  간선버스  서대구역(남측)1  DGB7061040400
3  동호공영차고지건너  DGB3000848000   848  간선버스   동호공영차고지앞  DGB7061040400
4    금구동(종점)  DGB3000649000   649  간선버스      대곡공원앞  DGB7061040400

In [54]:
df = df.drop(columns=['종점', '노선유형', '기점'])
df.head()

            노선ID  노선번호        node_id
0  DGB3000848001   848  DGB7061040400
1  DGB3000609007   609  DGB7061040400
2  DGB3000309002   309  DGB7061040400
3  DGB3000848000   848  DGB7061040400
4  DGB3000649000   649  DGB7061040400

In [57]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장하는 함수"""
    df_save = df.copy()

    # pandas 버전차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)  # str로 형변환

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : busapidb / table : {table_name}')

# 함수 호출
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료! 8행
DB : busapidb / table : route_by_stop

In [56]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')

CSV 저장 완료!