# 대구광역시 북구_공영주차장 운영 현황 및 현장 정보

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# --- 경로 설정 ---
# ipynb파일은 getcwd()함수를 이용해서 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking'

In [2]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'parking.csv') # 경로를 합침
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\input\\parking.csv'

In [3]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'parking_lot.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\output\\parking_lot.csv'

In [4]:
# --- PostgreSQL 연결 ---
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

In [5]:
# --- 데이터 수집 ---
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [6]:
df_raw.shape

(229, 27)

In [10]:
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [33]:
id_cols = ['주차장명', '소재지지번주소', '주차구획수']

In [34]:
df_long = pd.melt(
    df_raw,
    id_vars=id_cols,
)

df_long = df_long.drop(columns=['variable', 'value'])
df_long.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

In [35]:
def scale(count):
    if count < 20:
        return '소형'
    elif 20 <= count <= 50:
        return '중형'
    else:
        return '대형'

df_long['규모구분'] = df_long['주차구획수'].apply(scale)
df_long.head()

        주차장명               소재지지번주소  주차구획수 규모구분
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형

In [36]:
def fee(info):
    if info == '무료':
        return '무료'
    else:
        return '유료'
    
df_long['fee_type'] = df_raw['요금정보'].apply(fee)
df_long.head()

        주차장명               소재지지번주소  주차구획수 규모구분 fee_type
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료

In [16]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장"""
    df_save = df.copy()

    # pandas 버전차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)  # str로 형변환

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : parkingdb / table : {table_name}')

In [19]:
TABLE_NAME = 'parking_lot'

In [20]:
# 함수 호출
save_to_postgresql(df_long, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료! 5,496행
DB : parkingdb / table : parking_lot

In [21]:
df_long.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_long):,}행 x {len(df_long.columns)}열')

CSV 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\02_parking\output\parking_lot.csv
크기: 5,496행 x 3열