# 대구 지하철 승하차 데이터 수집 파이프라인 - csv파일 방식

## 전체 파이프라인 흐름
0. 환경설정 : 라이브러리 불러오기, 경로, DB URL 설정
1. 수집 : csv 파일 읽기 (인코딩 --> 윈도 cp949)
2. 변환 : 파일에 따라
3. 파생컬럼(파생변수) : ex) 시작시 / 날짜 / 요일코드 / 주말여부
4. 검증 : 유효성 검증 리포트 출력
5. DB 저장 : PostgreSQL -> subwaydb
6. csv 저장 : output폴더 안 csv파일 (utf-8-sig)

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# --- 경로 설정 ---
# ipynb파일은 getcwd()함수를 이용해서 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline'

In [ ]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'subway_raw.csv') # 경로를 합침
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline\\input\\subway_raw.csv'

In [3]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'subway_long.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline\\output\\subway_long.csv'

In [4]:
# --- PostgreSQL 연결 ---
DB_URL = 'postgresql://postgres:1234@localhost:5432/subwaydb'

## 공공데이터의 시간대별 데이터

### Wide
역명 | 승하 | 05시~06시 | 06~07시 | .... | 23시~24시 | 일계 |

설화명곡 | 승차 | 22 | 37 | .... | 47 | 2867 |

### Long
역명 | 승하 | 시간대컬럼 | 인원수 |
설화명곡 | 승차 | 05시~06시 | 22 |
설화명곡 | 승차 | 06시~07시 | 37 |

- Long 형태가 DB 저장, 시각화, 분석 모두에 적합하다.
- Long으로 변환하기 위해서 pd.melt() 를 사용한다.

In [5]:
# --- 요일 코드 매핑 ---
# dt.weekday 반환값 : 월==0, 화==1, ...
WEEKDAY_NAMES = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}

In [6]:
# --- 데이터 수집 ---
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,월,일,역번호,역명,승하차,05시-06시,06시-07시,07시-08시,08시-09시,09시-10시,...,15시-16시,16시-17시,17시-18시,18시-19시,19시-20시,20시-21시,21시-22시,22시-23시,23시-24시,일계
0,1,1,1150,설화명곡,승차,46,51,72,114,125,...,200,164,135,112,109,49,38,27,11,2194
1,1,1,1150,설화명곡,하차,4,84,39,70,86,...,150,182,189,186,147,113,98,124,77,2108
2,1,1,1160,화원,승차,27,39,47,91,138,...,218,204,167,85,69,51,38,32,7,2338
3,1,1,1160,화원,하차,3,83,63,64,149,...,207,215,156,124,91,107,90,79,57,2385
4,1,1,1170,대곡,승차,40,67,62,118,154,...,165,162,157,103,85,65,47,37,6,2205

In [7]:
# --- 행과 열의 개수 ---
df_raw.shape

(28388, 25)

In [8]:
# --- 열 이름 전체 확인 ---
for i, col in enumerate(df_raw.columns):
    print(f'[{i}] {col}')

[0] 월
[1] 일
[2] 역번호
[3] 역명
[4] 승하차
[5] 05시-06시
[6] 06시-07시
[7] 07시-08시
[8] 08시-09시
[9] 09시-10시
[10] 10시-11시
[11] 11시-12시
[12] 12시-13시
[13] 13시-14시
[14] 14시-15시
[15] 15시-16시
[16] 16시-17시
[17] 17시-18시
[18] 18시-19시
[19] 19시-20시
[20] 20시-21시
[21] 21시-22시
[22] 22시-23시
[23] 23시-24시
[24] 일계

In [9]:
# --- 데이터 타입 확인 ---
df_raw.dtypes

월          int64
일          int64
역번호        int64
역명           str
승하차          str
05시-06시    int64
06시-07시    int64
07시-08시    int64
08시-09시    int64
09시-10시    int64
10시-11시    int64
11시-12시    int64
12시-13시    int64
13시-14시    int64
14시-15시    int64
15시-16시    int64
16시-17시    int64
17시-18시    int64
18시-19시    int64
19시-20시    int64
20시-21시    int64
21시-22시    int64
22시-23시    int64
23시-24시    int64
일계         int64
dtype: object

In [11]:
# --- 결측치 확인 ---
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견')
    print(null_counts[null_counts > 0])
else:
    print('결측치 없음')

결측치 없음

In [13]:
id_cols = ['월', '일', '역번호', '역명', '승하차']
time_cols = [c for c in df_raw.columns if '시-' in c]

print(f'시간대별 컬럼 수 : {len(time_cols)}개')
print(f'시간대별 컬럼 목록 : {time_cols}')

시간대별 컬럼 수 : 19개
시간대별 컬럼 목록 : ['05시-06시', '06시-07시', '07시-08시', '08시-09시', '09시-10시', '10시-11시', '11시-12시', '12시-13시', '13시-14시', '14시-15시', '15시-16시', '16시-17시', '17시-18시', '18시-19시', '19시-20시', '20시-21시', '21시-22시', '22시-23시', '23시-24시']

## pd.melt() --> wide를 long으로 변환
df.melt(데이터프레임, id_vars=유지할 열, value_vals=행으로 만들 열,
var_name=새 열의 이름, value_name=값을 담을 새 열의 이름)

In [16]:
df_long = pd.melt(
    df_raw,
    id_vars=id_cols,
    value_vars=time_cols,
    var_name='시간대컬럼',
    value_name='인원수'
)

df_long = df_long.reset_index(drop=True)
df_long.shape

(539372, 7)

## 파생컬럼(파생변수) 추가

### 정규 표현식으로 숫자 추출
r'^(\d+)시'
- ^ : 문자열 맨 앞
- (\d+) : 숫자 하나 이상
- 시 : 시 글자
ex) 05시 == 5(int로 형 변환)

In [19]:
# --- 시작시 컬럼 추가 ---
# 05~06시 --> 앞의 숫자만 추출 --> 정수로 변환

df_long['시작시'] = df_long['시간대컬럼'].str.extract(r'^(\d+)시')[0].astype(int)
df_long['시작시']

0          5
1          5
2          5
3          5
4          5
          ..
539367    23
539368    23
539369    23
539370    23
539371    23
Name: 시작시, Length: 539372, dtype: int64

In [20]:
df_long.head()

   월  일   역번호    역명 승하차    시간대컬럼  인원수  시작시
0  1  1  1150  설화명곡  승차  05시-06시   46    5
1  1  1  1150  설화명곡  하차  05시-06시    4    5
2  1  1  1160    화원  승차  05시-06시   27    5
3  1  1  1160    화원  하차  05시-06시    3    5
4  1  1  1170    대곡  승차  05시-06시   40    5

In [21]:
# --- 날짜 컬럼 추가 ---
YEAR = 2026

df_long['월']

0         1
1         1
2         1
3         1
4         1
         ..
539367    5
539368    5
539369    5
539370    5
539371    5
Name: 월, Length: 539372, dtype: int64

## pd.to_datatime(dict)

- 연/월/일 딕셔너리를 한 번에 datetime으로 변환

In [22]:
df_series = pd.to_datetime(
    dict(year=YEAR, month=df_long['월'], day=df_long['일'])
)

df_series

0        2026-01-01
1        2026-01-01
2        2026-01-01
3        2026-01-01
4        2026-01-01
            ...
539367   2026-05-31
539368   2026-05-31
539369   2026-05-31
539370   2026-05-31
539371   2026-05-31
Length: 539372, dtype: datetime64[us]

In [23]:
df_long['날짜'] = df_series.dt.date

In [24]:
df_long.head()

   월  일   역번호    역명 승하차    시간대컬럼  인원수  시작시          날짜
0  1  1  1150  설화명곡  승차  05시-06시   46    5  2026-01-01
1  1  1  1150  설화명곡  하차  05시-06시    4    5  2026-01-01
2  1  1  1160    화원  승차  05시-06시   27    5  2026-01-01
3  1  1  1160    화원  하차  05시-06시    3    5  2026-01-01
4  1  1  1170    대곡  승차  05시-06시   40    5  2026-01-01

In [25]:
# --- 요일 코드 컬럼 추가 ---
df_series.dt.weekday # 월==0, 화==1, ...

0         3
1         3
2         3
3         3
4         3
         ..
539367    6
539368    6
539369    6
539370    6
539371    6
Length: 539372, dtype: int32

In [26]:
# .map(WEEKDAY_NAMES) --> 숫자로 된 요일번호가 한글 요일로 나온다.
df_long['요일코드'] = df_series.dt.weekday.map(WEEKDAY_NAMES)

df_long.head()

   월  일   역번호    역명 승하차    시간대컬럼  인원수  시작시          날짜 요일코드
0  1  1  1150  설화명곡  승차  05시-06시   46    5  2026-01-01    목
1  1  1  1150  설화명곡  하차  05시-06시    4    5  2026-01-01    목
2  1  1  1160    화원  승차  05시-06시   27    5  2026-01-01    목
3  1  1  1160    화원  하차  05시-06시    3    5  2026-01-01    목
4  1  1  1170    대곡  승차  05시-06시   40    5  2026-01-01    목

In [27]:
# --- 주말 여부 컬럼 추가 ---
# 토(5), 일(6) 이면 True
df_long['주말여부'] = df_series.dt.weekday >= 5

In [28]:
df_long.head()

   월  일   역번호    역명 승하차    시간대컬럼  인원수  시작시          날짜 요일코드   주말여부
0  1  1  1150  설화명곡  승차  05시-06시   46    5  2026-01-01    목  False
1  1  1  1150  설화명곡  하차  05시-06시    4    5  2026-01-01    목  False
2  1  1  1160    화원  승차  05시-06시   27    5  2026-01-01    목  False
3  1  1  1160    화원  하차  05시-06시    3    5  2026-01-01    목  False
4  1  1  1170    대곡  승차  05시-06시   40    5  2026-01-01    목  False

In [29]:
# --- 최종 컬럼의 목록 ---
df_long.columns

Index(['월', '일', '역번호', '역명', '승하차', '시간대컬럼', '인원수', '시작시', '날짜', '요일코드',
       '주말여부'],
      dtype='str')

In [30]:
# .tolist() : 리스트로 형 변환

df_long.columns.tolist()

['월', '일', '역번호', '역명', '승하차', '시간대컬럼', '인원수', '시작시', '날짜', '요일코드', '주말여부']

In [31]:
# --- 최종 데이터 타입 ---
df_long.dtypes

월         int64
일         int64
역번호       int64
역명          str
승하차         str
시간대컬럼       str
인원수       int64
시작시       int64
날짜       object
요일코드        str
주말여부       bool
dtype: object

## PostgreSQL 저장

1. PostgreSQL 서버가 실행 중인지 확인
2. subwaydb 데이터베이스가 있는지 확인
3. DB_URL 의 비밀번호가 맞는지 확인

In [32]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장"""
    df_save = df.copy()

    # pandas 버전차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)  # str로 형변환

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : subwaydb / table : {table_name}')

In [33]:
TABLE_NAME = 'subway_raw'

In [36]:
# 함수 호출
save_to_postgresql(df_long, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료! 539,372행
DB : subwaydb / table : subway_raw

## CSV 저장
- utf-8-sig

In [37]:
df_long.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_long):,}행 x {len(df_long.columns)}열')

CSV 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\01_subway_pipeline\output\subway_long.csv
크기: 539,372행 x 11열